// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

#ifdef RCPP_USE_GLOBAL_ROSTREAM
Rcpp::Rostream<true>&  Rcpp::Rcout = Rcpp::Rcpp_cout_get();
Rcpp::Rostream<false>& Rcpp::Rcerr = Rcpp::Rcpp_cerr_get();
#endif

// cpp_kfe_isotropic
double cpp_kfe_isotropic(NumericMatrix x, double g, int r1, int r2, bool kfe);
RcppExport SEXP _pmxcopula_cpp_kfe_isotropic(SEXP xSEXP, SEXP gSEXP, SEXP r1SEXP, SEXP r2SEXP, SEXP kfeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type g(gSEXP);
    Rcpp::traits::input_parameter< int >::type r1(r1SEXP);
    Rcpp::traits::input_parameter< int >::type r2(r2SEXP);
    Rcpp::traits::input_parameter< bool >::type kfe(kfeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_kfe_isotropic(x, g, r1, r2, kfe));
    return rcpp_result_gen;
END_RCPP
}
// cpp_kfe_isotropic_batch
NumericVector cpp_kfe_isotropic_batch(NumericMatrix x, double g, int r, bool kfe);
RcppExport SEXP _pmxcopula_cpp_kfe_isotropic_batch(SEXP xSEXP, SEXP gSEXP, SEXP rSEXP, SEXP kfeSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< double >::type g(gSEXP);
    Rcpp::traits::input_parameter< int >::type r(rSEXP);
    Rcpp::traits::input_parameter< bool >::type kfe(kfeSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_kfe_isotropic_batch(x, g, r, kfe));
    return rcpp_result_gen;
END_RCPP
}
// cpp_dmvnorm_mixture_eval
NumericVector cpp_dmvnorm_mixture_eval(NumericMatrix eval_points, NumericMatrix x, NumericMatrix H, NumericVector w);
RcppExport SEXP _pmxcopula_cpp_dmvnorm_mixture_eval(SEXP eval_pointsSEXP, SEXP xSEXP, SEXP HSEXP, SEXP wSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericMatrix >::type eval_points(eval_pointsSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type H(HSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_dmvnorm_mixture_eval(eval_points, x, H, w));
    return rcpp_result_gen;
END_RCPP
}
// cpp_kde_grid_truncated
NumericMatrix cpp_kde_grid_truncated(NumericVector gridx, NumericVector gridy, NumericMatrix x, NumericMatrix H, NumericVector w, double tolx, double toly);
RcppExport SEXP _pmxcopula_cpp_kde_grid_truncated(SEXP gridxSEXP, SEXP gridySEXP, SEXP xSEXP, SEXP HSEXP, SEXP wSEXP, SEXP tolxSEXP, SEXP tolySEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< NumericVector >::type gridx(gridxSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type gridy(gridySEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type x(xSEXP);
    Rcpp::traits::input_parameter< NumericMatrix >::type H(HSEXP);
    Rcpp::traits::input_parameter< NumericVector >::type w(wSEXP);
    Rcpp::traits::input_parameter< double >::type tolx(tolxSEXP);
    Rcpp::traits::input_parameter< double >::type toly(tolySEXP);
    rcpp_result_gen = Rcpp::wrap(cpp_kde_grid_truncated(gridx, gridy, x, H, w, tolx, toly));
    return rcpp_result_gen;
END_RCPP
}

static const R_CallMethodDef CallEntries[] = {
    {"_pmxcopula_cpp_kfe_isotropic", (DL_FUNC) &_pmxcopula_cpp_kfe_isotropic, 5},
    {"_pmxcopula_cpp_kfe_isotropic_batch", (DL_FUNC) &_pmxcopula_cpp_kfe_isotropic_batch, 4},
    {"_pmxcopula_cpp_dmvnorm_mixture_eval", (DL_FUNC) &_pmxcopula_cpp_dmvnorm_mixture_eval, 4},
    {"_pmxcopula_cpp_kde_grid_truncated", (DL_FUNC) &_pmxcopula_cpp_kde_grid_truncated, 7},
    {NULL, NULL, 0}
};

RcppExport void R_init_pmxcopula(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
