# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Kernel functional estimate for an isotropic bivariate normal kernel, for
#' all derivative-index combinations of a given order r at once (r=6 -> 7
#' combos, r=4 -> 5 combos)
#'
#' Computes the same O(n^2) pairwise-difference sum as
#' ks:::dmvnorm.deriv.sum(x, Sigma = g^2*diag(2), deriv.order = r, kfe =
#' kfe, binned = FALSE), for every derivative-index combination of order r
#' at once, sharing the pairwise-distance and exp() work across
#' combinations instead of redoing it per combination - only the Hermite
#' polynomial factor differs between them. Uses the closed-form isotropic
#' Hermite-polynomial derivative (D^(r1,r2) of an isotropic bivariate
#' normal collapses to a product of 1D Hermite polynomials) instead of
#' ks's general anisotropic tensor recursion - this is what ks::kfe() ends
#' up computing whenever it's called with an isotropic pilot bandwidth,
#' which is the only case ks::Hpi() uses for its "samse" pilot (the
#' default for 2D data). Validated in data-raw/validate_fast_hpi.R.
#'
#' @noRd
cpp_kfe_isotropic_batch <- function(x, g, r, kfe) {
    .Call(`_pmxcopula_cpp_kfe_isotropic_batch`, x, g, r, kfe)
}

#' Isotropic bivariate kernel functional estimate via linear binning + FFT
#' convolution
#'
#' Computes the same thing as ks:::kfe(x, G = g^2*diag(2), binned = TRUE,
#' deriv.order = r, deriv.vec = TRUE, add.index = FALSE) for r in {4, 6} -
#' the pilot-bandwidth kernel functional ks::Hpi() itself uses once n
#' exceeds ks:::default.bflag()'s ~500 threshold for 2D data. Mirrors
#' ks:::kdde.binned.nd() + ks:::symconv.nd() + the binned branch of
#' ks:::dmvnorm.deriv.sum() exactly: the kernel-grid evaluation (isotropic
#' closed form, same as cpp_kfe_isotropic_batch()) and the FFT convolution
#' are done here instead of via repeated R-level dmvnorm.deriv()/fft()
#' calls, which is what's actually slow in ks's own binned path (the linear
#' binning itself, via ks:::binning(), is already fast and is called from R
#' unchanged - see fast_kfe2d_binned() in R/internal_functions.R).
#' Validated in data-raw/validate_fast_hpi.R.
#'
#' @param counts Binned mass distribution (ks:::binning(x, H)$counts).
#' @param delta Bin grid spacing (dx, dy).
#' @param g,r Isotropic pilot bandwidth and derivative order.
#' @param n Sample size (sum of bin counts/weights).
#'
#' @noRd
cpp_kfe_isotropic_binned_batch <- function(counts, delta, g, r, n) {
    .Call(`_pmxcopula_cpp_kfe_isotropic_binned_batch`, counts, delta, g, r, n)
}

#' Weighted bivariate normal mixture density, evaluated at a set of points
#'
#' Computes the same thing as ks:::kde.points(x, H, eval.points, w)$estimate
#' (equivalently ks:::dmvnorm.mixt(x = eval.points, mus = x, Sigmas = H
#' repeated n times, props = w/n)$estimate) - the O(n^2) evaluation
#' ks::contourLevels.kde() falls back to for exact (approx = FALSE)
#' contour levels. H is a general (not necessarily isotropic) 2x2 matrix
#' here, unlike the isotropic-only kfe functions above.
#'
#' @noRd
cpp_dmvnorm_mixture_eval <- function(eval_points, x, H, w) {
    .Call(`_pmxcopula_cpp_dmvnorm_mixture_eval`, eval_points, x, H, w)
}

#' Unbinned bivariate kde grid evaluation, with the same support-window
#' truncation ks::kde() itself uses
#'
#' Computes the same thing as ks:::kde.grid.2d(x, H, gridx, ...)$estimate.
#' ks's version, for every data point, calls mvtnorm::dmvnorm() only on
#' the grid points within a box of half-width supp * diag(matrix.sqrt(H))
#' around that point (see ks:::make.supp(), ks:::find.gridpts()), skipping
#' cells far enough away for the Gaussian kernel to be negligible there.
#' This replicates that same box (tolx, toly, computed in R exactly as ks
#' does) using direct index arithmetic instead of a linear index search
#' (valid since the grid is evenly spaced), and the same closed-form
#' density for points inside the box, without going through
#' mvtnorm::dmvnorm() or R-level loops.
#'
#' @param gridx,gridy Grid coordinates, evenly spaced (as ks::kde() uses by
#' default).
#' @param x,H,w As elsewhere - the fitted data, bandwidth and weights.
#' @param tolx,toly Support window half-widths, supp * diag(matrix.sqrt(H)).
#'
#' @noRd
cpp_kde_grid_truncated <- function(gridx, gridy, x, H, w, tolx, toly) {
    .Call(`_pmxcopula_cpp_kde_grid_truncated`, gridx, gridy, x, H, w, tolx, toly)
}

